apiVersion: 1

datasources:
  - name: Forecasting Postgres
    type: postgres
    access: proxy
    url: forecasting-postgres-database:5432
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_SECRET}
    jsonData:
      database: ${DB_NAME}
      sslmode: disable
    isDefault: true