apiVersion: apps/v1
kind: Deployment
metadata:
  name: sender-deployment
  labels:
    app: traffic-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-sender
  template:
    metadata:
      labels:
        app: traffic-sender
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: sender
          image: alpine
          command: ["/bin/sh", "-c"]
          args: ["while true; do wget -qO- http://receiver-service:8080; sleep 2; done"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-deployment
  labels:
    app: traffic-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-receiver
  template:
    metadata:
      labels:
        app: traffic-receiver
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: receiver
          image: hashicorp/http-echo
          args:
            - "-text=hello"
            - "-listen=:8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sender-service
spec:
  selector:
    app: traffic-sender
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-service
spec:
  selector:
    app: traffic-receiver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

