apiVersion: v1
kind: Service
metadata:
  labels:
    app: orchestrator
  name: orchestrator
spec:
  type: NodePort
  ports:
  - name: http
    port: 8000
    targetPort: 80
    nodePort: 30080
  selector:
    app: orchestrator

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
      - image: kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
          name: http