prometheus:
  persistence:
    enabled: false
#    enabled: true
#    size: 5Gi          # Set the desired size for your Prometheus data
#    storageClass: ""    # Leave it empty to use the default StorageClass, or specify your own class
#    accessModes:
#      - ReadWriteOnce
  extraScrapeConfigs:
    - job_name: 'kubernetes-kubelet'
      scheme: https
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/resource
    - job_name: 'kubernetes-cadvisor'
      scheme: https
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
#    - job_name: 'sender'
#      static_configs:
#        - targets: ['sender-service.default.svc.cluster.local:8000']
