{
 "title": "AI-forecassting-platform",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Historical data from Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "cpu usage upf",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "forecasting",
     "rawSql": "SELECT *\nFROM input \nWHERE metric_name='cpu_usage_upf'\nORDER BY datetime DESC"
    }
   ]
  },
  {
   "title": "memory usage upf",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "dataset": "forecasting",
     "rawSql": "SELECT *\nFROM input \nWHERE metric_name='memory_usage_upf'\nORDER BY datetime DESC"
    }
   ]
  },
  { "title": "data repetition", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "forecasting",
     "rawSql": "SELECT metric_name, value, datetime, count(*) AS frequency\nFROM input \nWHERE metric_name='cpu_usage_upf'\nGROUP BY datetime, metric_name, value\nORDER BY datetime DESC"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dataset": "forecasting",
     "rawSql": "SELECT metric_name, value, datetime, count(*) AS frequency\nFROM input \nWHERE metric_name='memory_usage_upf'\nGROUP BY datetime, metric_name, value\nORDER BY datetime DESC"
    }
   ]
  },
  {
   "title": "Forecast data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true
  },
  {
   "title": "forecast cpu usage upf",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "forecasting",
     "rawSql": "select * FROM forecasted WHERE metric_name='cpu_usage_upf' ORDER BY datetime DESC"
    }
   ]
  },
  {
   "title": "forecast memory usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "dataset": "forecasting",
     "rawSql": "select * FROM forecasted WHERE metric_name='memory_usage_upf' ORDER BY datetime DESC"
    }
   ]
  },
  { "title": "Plots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "cpu usage upf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "dataset": "forecasting",
     "rawSql": "SELECT *\nFROM input \nWHERE metric_name='cpu_usage_upf'\nORDER BY datetime DESC"
    },
    {
     "dataset": "forecasting",
     "rawSql": "SELECT value as forecasted_value, datetime as time\nFROM forecasted \nWHERE metric_name = 'cpu_usage_upf'"
    },
    {
     "dataset": "forecasting",
     "rawSql": "SELECT DISTINCT\n  datetime,\n  metric_name,\n  AVG(value) OVER (PARTITION BY metric_name) AS avg_value\nFROM input\nWHERE metric_name = 'cpu_usage_upf'\nORDER BY datetime DESC;"
    },
    {
     "dataset": "forecasting",
     "rawSql": "SELECT\n    datetime,\n    metric_name,\n    max(value) OVER (\n        PARTITION BY metric_name, \n                     FLOOR(EXTRACT(EPOCH FROM datetime) / 300)\n    ) AS max_value_5min\nFROM input\nWHERE metric_name = 'cpu_usage_upf'\nORDER BY datetime DESC;"
    }
   ]
  },
  {
   "title": "memory usage upf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "dataset": "forecasting",
     "rawSql": "SELECT *\nFROM input \nWHERE metric_name='memory_usage_upf'\nORDER BY datetime DESC"
    }
   ]
  }
 ]
}