version: '3'

volumes:
  prefect_db_volume:
  flow_storage_volume:
  forecasting_postgres:

networks:
  6g-core-network:

services:

  # data/metrics exporter
  metrics_exporter:
    container_name: metrics-exporter
    build: 
      context: "./prometheus_metrics"
      dockerfile: Dockerfile
    network_mode: "host"
    ports:
      - "8000:8000"
    profiles: ["prometheus", "compose-project"]

  # system/service monitoring system
  # prometheus:
  #   container_name: prometheus
  #   image: prom/prometheus
  #   networks:
  #     - 6g-core-network
  #   volumes:
  #     - ./prometheus_metrics/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   profiles: ["prometheus", "compose-project"]

  # prefect database
  prefect_db:
    container_name: prefect_db
    hostname: prefect_db
    image: postgres:15.2-alpine
    restart: unless-stopped
    networks:
      - 6g-core-network
    #ports:
    #  - 5432:5432
    environment:
      POSTGRES_USER: ${PREFECT_DB_USER}
      POSTGRES_PASSWORD: ${PREFECT_DB_SECRET}
      POSTGRES_DB: ${PREFECT_DB_NAME}
    volumes:
      - prefect_db_volume:/var/lib/postgresql/data
    profiles: ["prefect-orion", "compose-project"]

  # prefect server
  prefect-orion:
    container_name: prefect_orion
    hostname: prefect_orion
    build:
      context: "./prefect-server"
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - 6g-core-network
    entrypoint: [ "prefect", "server", "start", "--host", "${PREFECT_SERVER_HOSTNAME}" ]
    environment:
      - PREFECT_ORION_API_HOST=${PREFECT_SERVER_HOSTNAME}
      - PREFECT_ORION_API_PORT=${PREFECT_SERVER_PORT}
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://${PREFECT_DB_USER}:${PREFECT_DB_SECRET}@${PREFECT_DB_HOST}:${PREFECT_DB_PORT}/${PREFECT_DB_NAME}
    ports:
      - 4200:4200
    depends_on:
      - prefect_db
    profiles: ["prefect-orion", "compose-project"]

  # prefect worker
  prefect-worker:
    container_name: prefect_worker
    build:
      context: "./prefect-worker"
      dockerfile: Dockerfile
    network_mode: "host"
    restart: unless-stopped
    entrypoint: [ "prefect", "agent", "start", "--pool", "LSTM_forecasting" ]
    env_file: ".env"
    profiles: ["prefect-worker"]

  # Prefect CLI
  prefect-cli:
    container_name: prefect_cli
    build:
      context: "."
      dockerfile: prefect-cli/Dockerfile
    entrypoint: "bash"
    working_dir: "/root/flows"
    network_mode: "host"
    volumes:
      - ./scripts:/root/flows/scripts
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL} # do not change name of this variable
    profiles: ["prefect-cli"]

  # minio
  minio:
    container_name: minio
    hostname: minio
    networks:
      - 6g-core-network
    restart: unless-stopped
    image: bitnami/minio:2023.1.31-debian-11-r2
    volumes:
      - flow_storage_volume:/data
    ports:
      - 9000:9000
      - 9001:9001
    env_file: ".env"
    profiles: ["minio", "compose-project"]

  # postgres for monitoring data and predictions
  forecasting-postgres-database:
    container_name: forecasting-postgres-database
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_SECRET}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - 6g-core-network
    ports:
      - '5432:5432'
    volumes:
      - forecasting_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    profiles: ["postgres", "compose-project"]

  # # orchestrator
  # orchestrator:
  #   container_name: orchestrator
  #   image: kennethreitz/httpbin
  #   networks:
  #     - 6g-core-network
  #   ports:
  #     - "80:80"
  #   profiles: ["orchestrator", "compose-project"]